name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Validate Gradle wrapper
      with:
        lfs: true  # gradle-wrapper.jar verification will fail without this
      uses: gradle/actions/wrapper-validation@v6
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Run tests
      run: ./gradlew testDebugUnitTest
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: ${{ !contains(github.ref, 'release') }}
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: ${{ !contains(github.ref, 'release') }}
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
